export async function exportPDF(content: string, title: string): Promise<Buffer> {
  // puppeteer is optional — install separately on server if needed
  const html = buildHTML(content, title);

  // Try to use puppeteer if available at runtime
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const puppeteer = require("puppeteer");
    const browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    const pdf = await page.pdf({
      format: "A4",
      margin: { top: "20mm", right: "20mm", bottom: "20mm", left: "20mm" },
      printBackground: true,
    });
    await browser.close();
    return Buffer.from(pdf);
  } catch {
    // Fallback: return HTML as buffer (browser can print to PDF)
    return Buffer.from(html, "utf-8");
  }
}

function buildHTML(content: string, title: string): string {
  return `<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 13px; line-height: 1.7; color: #1a1a1a; max-width: 800px; margin: 0 auto; padding: 40px 48px; }
    h1 { font-size: 2em; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; margin-top: 0; }
    h2 { font-size: 1.4em; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; margin-top: 2em; color: #111827; }
    h3 { font-size: 1.1em; color: #374151; }
    code { background: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }
    pre { background: #f3f4f6; padding: 16px; border-radius: 8px; overflow-x: auto; }
    pre code { background: none; padding: 0; }
    table { border-collapse: collapse; width: 100%; margin: 1em 0; }
    th, td { border: 1px solid #d1d5db; padding: 8px 12px; text-align: left; }
    th { background: #f9fafb; font-weight: 600; }
    blockquote { border-left: 4px solid #6366f1; margin: 0; padding: 8px 16px; background: #f5f3ff; color: #4b5563; }
    ul, ol { padding-left: 1.5em; }
    li { margin: 4px 0; }
    .watermark { position: fixed; bottom: 20px; right: 20px; font-size: 10px; color: #9ca3af; }
  </style>
</head>
<body>
  <div id="content">${markdownToHtml(content)}</div>
  <div class="watermark">Generated by PRD Generator</div>
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function markdownToHtml(markdown: string): string {
  return markdown
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/^> (.+)$/gm, "<blockquote>$1</blockquote>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, "<ul>$&</ul>")
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    .replace(/\n\n/g, "</p><p>")
    .replace(/^(?!<[hup]|<li|<block)(.+)$/gm, "<p>$1</p>")
    .replace(/<p><\/p>/g, "");
}
